version: '3'

services:
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "127.0.0.1:3306:3306"
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test-db
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes: 
  mysql-data:
    driver: local